const comments = [
  { id: 1, name: 'Lina Nguyen', initials: 'LN', avatar: 'avatar-lina', location: 'Amsterdam, NL', time: '8 min ago', timestamp: 8, text: 'Our Friday demos became the thing I look forward to most. No slides, just a small win from each person and ten minutes to celebrate it together.', likes: 18, dislikes: 1, replies: 2, edited: false, language: 'English', reply: { name: 'Diego Santos', initials: 'DS', avatar: 'avatar-diego', location: 'Madrid, ES', time: '4 min ago', text: 'Same here. We call ours “the little victories” and it has made a huge difference.', likes: 5 } },
  { id: 2, name: 'Diego Santos', initials: 'DS', avatar: 'avatar-diego', location: 'Madrid, ES', time: '21 min ago', timestamp: 21, text: 'Para nosotros, cocinar juntos una vez al mes ha sido increíble. La comida nos da una forma sencilla de conocernos fuera del trabajo.', translation: 'For us, cooking together once a month has been incredible. Food gives us a simple way to get to know each other outside of work.', likes: 14, dislikes: 0, replies: 1, edited: true, language: 'Spanish' },
  { id: 3, name: 'Sana Khan', initials: 'SK', avatar: 'avatar-sana', location: 'Bengaluru, IN', time: '42 min ago', timestamp: 42, text: 'I’m curious how teams make space for quieter voices in these rituals. A chat prompt before the call has helped our introverts arrive with something ready to share.', likes: 22, dislikes: 0, replies: 3, edited: false, language: 'English' },
  { id: 4, name: 'Jules Park', initials: 'JP', avatar: 'avatar-jules', location: 'Seoul, KR', time: '1 hr ago', timestamp: 60, text: 'We send a tiny postcard to a teammate every month. It sounds old-fashioned, but a physical reminder that someone is thinking of you lands differently.', likes: 11, dislikes: 0, replies: 0, edited: false, language: 'English' },
  { id: 5, name: 'Mara Costa', initials: 'MC', avatar: 'avatar-lina', location: 'Lisbon, PT', time: '2 hrs ago', timestamp: 120, text: 'A rotating “host” makes async weeks feel less like a pile of tasks. @SanaKhan’s idea of a prompt would fit beautifully here.', likes: 9, dislikes: 0, replies: 0, edited: false, language: 'English' },
  { id: 6, name: 'Tom Becker', initials: 'TB', avatar: 'avatar-diego', location: 'Berlin, DE', time: '3 hrs ago', timestamp: 180, text: 'We keep one channel just for photos of where we are working. It is a low-effort way to make the distance visible, in a good way.', likes: 7, dislikes: 0, replies: 0, edited: false, language: 'English' },
  { id: 7, name: 'Nadia Ali', initials: 'NA', avatar: 'avatar-sana', location: 'Dubai, AE', time: 'Yesterday', timestamp: 1440, text: 'Un paseo virtual con una pregunta diferente cada week has helped us practice curiosity. Small consistency beats a big event.', likes: 4, dislikes: 0, replies: 0, edited: false, language: 'English' },
  { id: 8, name: 'Owen Wright', initials: 'OW', avatar: 'avatar-jules', location: 'Toronto, CA', time: 'Yesterday', timestamp: 1500, text: 'The best ritual is making room for no agenda at all. Sometimes presence is the whole point.', likes: 3, dislikes: 0, replies: 0, edited: false, language: 'English' }
];
const translations = { Spanish: 'English translation', English: 'Spanish translation' };
const commentsList = document.querySelector('#commentsList');
const sortSelect = document.querySelector('#sortSelect');
const composer = document.querySelector('#composer');
const toast = document.querySelector('#toast');

function icon(name) { return `<i data-lucide="${name}"></i>`; }
function renderComments() {
  const sorted = [...comments].sort((a, b) => sortSelect.value === 'newest' ? a.timestamp - b.timestamp : sortSelect.value === 'oldest' ? b.timestamp - a.timestamp : sortSelect.value === 'liked' ? b.likes - a.likes : a.id - b.id);
  commentsList.innerHTML = sorted.map(comment => `<article class="comment" data-id="${comment.id}"><div class="avatar ${comment.avatar}">${comment.initials}</div><div class="comment-body"><div class="comment-header"><strong>${comment.name}</strong><span class="comment-location">${comment.location}</span><span class="comment-time">· ${comment.time}</span>${comment.edited ? '<span class="edited">Edited</span>' : ''}</div><p class="comment-text">${highlightMentions(comment.text)}</p>${comment.translation ? `<div class="translation"><strong>${icon('languages')} ${translations[comment.language]}</strong>${comment.translation}</div>` : ''}<div class="comment-tools"><button class="comment-action vote-button ${comment.userVote === 'like' ? 'voted' : ''}" data-vote="like">${icon('thumbs-up')}<span>${comment.likes}</span></button><button class="comment-action vote-button ${comment.userVote === 'dislike' ? 'voted' : ''}" data-vote="dislike">${icon('thumbs-down')}<span>${comment.dislikes || 0}</span></button><button class="comment-action reply-button">${icon('corner-up-left')} Reply</button><button class="comment-action translate-button">${icon('languages')} ${comment.translation ? 'Hide translation' : 'Translate'}</button><button class="comment-action more-button" aria-label="More actions">${icon('more-horizontal')}</button></div>${comment.reply ? `<div class="reply-thread"><div class="comment"><div class="avatar ${comment.reply.avatar}">${comment.reply.initials}</div><div class="comment-body"><div class="comment-header"><strong>${comment.reply.name}</strong><span class="comment-location">${comment.reply.location}</span><span class="comment-time">· ${comment.reply.time}</span></div><p class="comment-text">${comment.reply.text}</p><div class="comment-tools"><button class="comment-action">${icon('thumbs-up')} ${comment.reply.likes}</button><button class="comment-action">${icon('corner-up-left')} Reply</button></div></div></div></div>` : ''}</div></article>`).join('');
  document.querySelector('#commentCount').textContent = `${comments.length} comments`;
  lucide.createIcons();
  commentsList.querySelectorAll('.vote-button').forEach(button => button.addEventListener('click', vote));
  commentsList.querySelectorAll('.translate-button').forEach(button => button.addEventListener('click', translate));
  commentsList.querySelectorAll('.reply-button').forEach(button => button.addEventListener('click', () => { composer.classList.remove('hidden'); document.querySelector('#commentInput').focus(); }));
  commentsList.querySelectorAll('.more-button').forEach(button => button.addEventListener('click', () => { const comment = comments.find(item => item.id === Number(button.closest('.comment').dataset.id)); if (comment.name === 'Alex Morgan') { showToast('Edit and delete are available for 10 minutes'); } else { document.querySelector('#reportModal').classList.remove('hidden'); document.querySelector('#reportModal').dataset.commentId = comment.id; } }));
}
function highlightMentions(text) { return text.replace(/@([a-z0-9]+)/gi, '<span class="mention">@$1</span>'); }
function vote(event) { const comment = comments.find(item => item.id === Number(event.currentTarget.closest('.comment').dataset.id)); const voteType = event.currentTarget.dataset.vote; if (comment.userVote === voteType) { comment[voteType === 'like' ? 'likes' : 'dislikes']--; comment.userVote = null; } else { if (comment.userVote) comment[comment.userVote === 'like' ? 'likes' : 'dislikes']--; comment[voteType === 'like' ? 'likes' : 'dislikes']++; comment.userVote = voteType; } renderComments(); }
function translate(event) { const comment = comments.find(item => item.id === Number(event.currentTarget.closest('.comment').dataset.id)); if (comment.translation) { comment.translation = ''; } else { comment.translation = comment.language === 'Spanish' ? 'For us, cooking together once a month has been incredible. Food gives us a simple way to get to know each other outside of work.' : 'Translation preview: ' + comment.text; } renderComments(); showToast(comment.translation ? 'Translation ready' : 'Translation hidden'); }
function showToast(message) { toast.querySelector('span').textContent = message; toast.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => toast.classList.remove('show'), 2400); }

document.querySelector('#openComposer').addEventListener('click', () => { composer.classList.remove('hidden'); document.querySelector('#commentInput').focus(); });
document.querySelector('#closeComposer').addEventListener('click', () => composer.classList.add('hidden'));
document.querySelector('#closeReport').addEventListener('click', () => document.querySelector('#reportModal').classList.add('hidden'));
document.querySelector('#submitReport').addEventListener('click', () => { const reason = document.querySelector('#reportReason').value; document.querySelector('#reportModal').classList.add('hidden'); showToast(`Report logged for moderator review: ${reason}`); });
sortSelect.addEventListener('change', renderComments);
document.querySelector('#postComment').addEventListener('click', () => { const input = document.querySelector('#commentInput'); const text = input.value.trim(); const message = document.querySelector('#composerMessage'); if (text.length < 8) { message.textContent = 'Add a little more detail before posting.'; return; } if (/https?:\/\/|www\./i.test(text)) { message.textContent = 'Links need moderator approval before they can be posted.'; return; } if (comments.some(comment => comment.text.toLowerCase() === text.toLowerCase())) { message.textContent = 'This looks like a duplicate comment.'; return; } comments.unshift({ id: Date.now(), name: 'Alex Morgan', initials: 'AM', avatar: 'avatar-user', location: 'New York, US', time: 'just now', timestamp: 0, text, likes: 0, dislikes: 0, replies: 0, edited: false, language: 'English' }); input.value = ''; message.textContent = ''; composer.classList.add('hidden'); sortSelect.value = 'newest'; renderComments(); showToast('Comment posted and checked'); });
renderComments(); lucide.createIcons();
