const videos = [
  { id: 'flowers', title: 'Flowers in the morning', description: 'A close-up study of flowers opening into the first light.', duration: '12:48', src: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', thumbnail: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=640&q=80', color: '#765d68' },
  { id: 'bunny', title: 'Big Buck Bunny', description: 'A playful animated animal adventure through a sunny meadow.', duration: '09:56', src: 'https://media.w3.org/2010/05/bunny/trailer.mp4', thumbnail: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=640&q=80', color: '#536b58' },
  { id: 'wildlife', title: 'Wildlife in the meadow', description: 'A gentle field note for curious eyes and quiet afternoons.', duration: '15:04', src: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4', thumbnail: 'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=640&q=80', color: '#3f526b' }
];
const state = { index: 0, timer: null, idleTimer: null, loadTimer: null, autoplay: false, captions: false };
const video = document.querySelector('#video');
const $ = (id) => document.querySelector(id);
const formatTime = (seconds) => { if (!Number.isFinite(seconds)) return '0:00'; const mins = Math.floor(seconds / 60); const secs = Math.floor(seconds % 60).toString().padStart(2, '0'); return `${mins}:${secs}`; };
function savedPosition() { return Number(localStorage.getItem(`framehouse-position-${videos[state.index].id}`) || 0); }
function updateProgress() { const percent = video.duration ? (video.currentTime / video.duration) * 100 : 0; $('#timeline').value = percent; $('#currentTime').textContent = formatTime(video.currentTime); $('#duration').textContent = formatTime(video.duration); $('#watchProgress').style.width = `${percent}%`; $('#progressLabel').textContent = `${Math.round(percent)}% watched`; if (video.buffered.length) $('#bufferBar').style.width = `${(video.buffered.end(video.buffered.length - 1) / video.duration) * 100}%`; if (video.currentTime > 0 && Math.round(video.currentTime) % 5 === 0) localStorage.setItem(`framehouse-position-${videos[state.index].id}`, video.currentTime); }
function showMediaError() { clearTimeout(state.loadTimer); $('#loadingState').style.display = 'none'; $('#mediaError').style.display = 'flex'; }
function setVideo(index, showResume = true) { clearTimeout(state.loadTimer); state.index = (index + videos.length) % videos.length; const item = videos[state.index]; video.src = item.src; video.poster = item.thumbnail; $('#videoTitle').textContent = item.title; $('#videoDescription').textContent = item.description; $('#headerDuration').textContent = item.duration; $('#nextTitle').textContent = videos[(state.index + 1) % videos.length].title; renderPlaylist(); $('#mediaError').style.display = 'none'; $('#loadingState').style.display = 'flex'; video.load(); state.loadTimer = setTimeout(showMediaError, 12000); const position = savedPosition(); if (showResume && position > 4) { $('#resumeTime').textContent = formatTime(position); $('#resumeToast').classList.add('show'); setTimeout(() => $('#resumeToast').classList.remove('show'), 4500); } }
function renderPlaylist() { $('#playlist').innerHTML = videos.map((item, index) => { const position = Number(localStorage.getItem(`framehouse-position-${item.id}`) || 0); return `<div class="playlist-item ${index === state.index ? 'active' : ''}" data-index="${index}"><img class="thumb" src="${item.thumbnail}" alt="${item.title} thumbnail"><div><h4>${item.title}</h4><p>${item.duration} · ${index === state.index ? 'Now playing' : 'Field note'}</p><div class="item-progress"><span style="width:${Math.min(100, (position / 600) * 100)}%"></span></div></div></div>`; }).join(''); document.querySelectorAll('.playlist-item').forEach((el) => el.addEventListener('click', () => { setVideo(Number(el.dataset.index), false); video.play().catch(() => {}); })); }
function togglePlay() { if (video.paused) video.play().catch(() => {}); else video.pause(); }
function seek(amount) { video.currentTime = Math.max(0, Math.min(video.duration || 0, video.currentTime + amount)); updateProgress(); }
function updatePlayState() { const playing = !video.paused; $('#playButton').textContent = playing ? '❚❚' : '▶'; $('#playButton').setAttribute('aria-label', playing ? 'Pause' : 'Play'); $('#centerPlay').style.display = playing ? 'none' : 'grid'; }
function nextVideo() { clearInterval(state.timer); state.autoplay = false; $('#autoplayPanel').style.display = 'none'; setVideo(state.index + 1, false); video.play().catch(() => {}); }
function startAutoplay() { if (state.autoplay) return; state.autoplay = true; let count = 8; $('#autoplayPanel').style.display = 'grid'; $('#countdown').textContent = count; $('#countdownText').textContent = count; state.timer = setInterval(() => { count -= 1; $('#countdown').textContent = count; $('#countdownText').textContent = count; if (count <= 0) nextVideo(); }, 1000); }
function showUi() { $('#videoFrame').classList.remove('idle'); clearTimeout(state.idleTimer); state.idleTimer = setTimeout(() => { if (!video.paused) $('#videoFrame').classList.add('idle'); }, 3000); }
video.addEventListener('loadedmetadata', () => { clearTimeout(state.loadTimer); $('#loadingState').style.display = 'none'; $('#mediaError').style.display = 'none'; $('#headerDuration').textContent = formatTime(video.duration); const position = savedPosition(); if (position > 4 && position < video.duration - 5) video.currentTime = position; updateProgress(); });
video.addEventListener('timeupdate', updateProgress); video.addEventListener('progress', updateProgress); video.addEventListener('play', updatePlayState); video.addEventListener('pause', updatePlayState); video.addEventListener('error', showMediaError); video.addEventListener('ended', () => { localStorage.setItem(`framehouse-position-${videos[state.index].id}`, video.duration); startAutoplay(); updatePlayState(); }); video.addEventListener('waiting', () => $('#loadingState').style.display = 'flex'); video.addEventListener('playing', () => { clearTimeout(state.loadTimer); $('#loadingState').style.display = 'none'; });
$('#playButton').addEventListener('click', togglePlay); $('#centerPlayButton').addEventListener('click', togglePlay); $('#backButton').addEventListener('click', () => seek(-10)); $('#forwardButton').addEventListener('click', () => seek(10)); $('#timeline').addEventListener('input', (event) => { video.currentTime = (Number(event.target.value) / 100) * video.duration; updateProgress(); }); $('#volume').addEventListener('input', (event) => { video.volume = Number(event.target.value); video.muted = video.volume === 0; $('#muteButton').textContent = video.muted ? '◌' : '◖'; }); $('#muteButton').addEventListener('click', () => { video.muted = !video.muted; $('#muteButton').textContent = video.muted ? '◌' : '◖'; }); $('#fullscreenButton').addEventListener('click', () => document.fullscreenElement ? document.exitFullscreen() : $('#videoFrame').requestFullscreen()); $('#theaterButton').addEventListener('click', () => document.body.classList.toggle('theater')); $('#pipButton').addEventListener('click', async () => { if (document.pictureInPictureElement) await document.exitPictureInPicture(); else if (document.pictureInPictureEnabled) await video.requestPictureInPicture(); }); $('#cancelAutoplay').addEventListener('click', () => { clearInterval(state.timer); state.autoplay = false; $('#autoplayPanel').style.display = 'none'; }); $('#restartButton').addEventListener('click', () => { video.currentTime = 0; localStorage.removeItem(`framehouse-position-${videos[state.index].id}`); $('#resumeToast').classList.remove('show'); }); $('#saveButton').addEventListener('click', (event) => { event.currentTarget.textContent = '✓ Saved to library'; });
$('#timeline').addEventListener('mousemove', (event) => { const rect = event.currentTarget.getBoundingClientRect(); const percent = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); $('#previewCard').style.left = `${percent * 100}%`; $('#previewCard').style.display = 'block'; $('#previewTime').textContent = formatTime(percent * video.duration); }); $('#timeline').addEventListener('mouseleave', () => $('#previewCard').style.display = 'none'); document.querySelector('#videoFrame').addEventListener('mousemove', showUi); document.querySelector('#videoFrame').addEventListener('touchstart', showUi);
document.addEventListener('keydown', (event) => { if (['INPUT', 'BUTTON'].includes(document.activeElement.tagName)) return; const amount = event.shiftKey ? 30 : 10; switch (event.key.toLowerCase()) { case ' ': event.preventDefault(); togglePlay(); break; case 'arrowleft': seek(-amount); break; case 'arrowright': seek(amount); break; case 'arrowup': event.preventDefault(); $('#volume').value = Math.min(1, Number($('#volume').value) + .05); $('#volume').dispatchEvent(new Event('input')); break; case 'arrowdown': event.preventDefault(); $('#volume').value = Math.max(0, Number($('#volume').value) - .05); $('#volume').dispatchEvent(new Event('input')); break; case 'm': $('#muteButton').click(); break; case 'f': $('#fullscreenButton').click(); break; case 't': $('#theaterButton').click(); break; case 'c': $('#captionsButton').classList.toggle('active'); state.captions = !state.captions; break; case 'n': nextVideo(); break; case '>': video.playbackRate = video.playbackRate >= 2 ? .5 : video.playbackRate + .25; break; } });
$('#qualityButton').addEventListener('click', () => { const qualities = ['1080p HD', '720p', '480p']; const current = qualities.indexOf($('#qualityButton').textContent); $('#qualityButton').textContent = qualities[(current + 1) % qualities.length]; }); $('#speedButton').addEventListener('click', () => { const speeds = [.5, 1, 1.25, 1.5, 2]; const current = speeds.indexOf(video.playbackRate); const next = speeds[(current + 1) % speeds.length]; video.playbackRate = next; $('#speedButton').textContent = `${next}×`; }); $('#captionsButton').addEventListener('click', () => { state.captions = !state.captions; $('#captionsButton').classList.toggle('active', state.captions); }); $('#autoplayPanel').style.display = 'none'; video.volume = .8; setVideo(0); updatePlayState();
